name: Reusable Workflow
on: 
    workflow_call:
        
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Print Console
              run: echo " Deploying Application...."