name: Test Workflow
on:
  workflow_dispatch

jobs:
 
  test:
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: exit 1
        id:  fail
        continue-on-error: true

      - name: step2
        if: steps.fail.outcome == 'failure'
        run: echo "A previous step failed"

  print:
    runs-on: ubuntu-latest
    steps:
      - name: console print
        run: echo "printing to console"
  
  
